#
# Travis CI configuration file
#

language: python
python:
- '2.7'
- '3.6'
- '3.7'
- '3.8'
- '3.9'
- pypy3
install:
  - pip install tox-travis
sudo: false
script: tox


#
# Deploy
#

deploy:
  provider: pypi
  user: __token__
  password:
    secure: XAh3dqw3iy6dDrkBjLAn5b1/yK9EgW3BdHirIxBG8QIvTi39fQMwf6TR4fLJ20SCpd92RnQV9WxfYidkq07Yr9jDvg5efiIl3B0rMTnNzo+3oTv39mOE5DawWnFj/1wd+SM0sYCF3DRYG7Dv1Y6SAGw4Qg0behXVCwS7HPVdRg0E26A09LzusNTWMJtjbaN/D3lHGd5zeyE4cSKBYMXCMfTcfldzv/0nuqT4vbGN4EisC8SeWdDYHORmLAVKDpoEqatDoCXGvJ/1fJV1+adIoOkaJjkqVDGibRZmErZEW03g0JZYRhqSaBqAFGpPQJ9nT4KHAsqhHE2jJPYwi5yJOJ1KxX1pqfu4Ua0kP9urJWK2Q6lCMBfj1xwHWGRYYquE2dldF/60jzFPuv/9CHDjS9Vd07Xr/rKZTL7hK1XYf31fApmIYoI9rJpv4DPZcxK7wwBGI2UGRlehyb2ttEqQZ04DGdRfhE5C4ejwzESeb5F10cER8tl/gELikWcJyS/LrlH20eJIiQELhGumsnJ/YN/d8ztpx73idWMEqKXlFqfOQsIJ6wlwGDskDk0N8dmUR5sBGpMLsipUW/r96GqEDFt6hzctN5yd9almuH0FzLJxgzG394ukByLQiaW5weDt9Clu+7Yapmbvc0Rs4stnE30KNoeRD/YAGHdLoXN1+lU=
  skip_existing: true
  on:
    tags: true


#
# Meta
#

branches:
  only:
  - master
  # Also on tags, so that deploys are triggered.
  # (This regex matches semantic versions like v1.2.3-rc4+2016.02.22)
  - /^\d+\.\d+(\.\d+)?.*$/
git:
  # Don't set this to 1
  # (see note at https://docs.travis-ci.com/user/customizing-the-build#Git-Clone-Depth)
  depth: 5
cache:
- pip
